general_constant = {
    # threshold to determine when discard the sample because it imports few APIs that we can inject
    "threshold_imported_api": 0.01,
    "max_it_number": 600, # max number of iterations for the attack
    "n_pools": 3, # number of pools to use for the attack
    "min_valid_apis": 75, # min number of APIs that a sequence must contain

    # List of APIs that we can inject
    "apis_we_can_inject":  ["HttpOpenRequestW", "WSASocketA", "RegOpenKeyExW", "RemoveDirectoryA", 
                            "NtOpenProcess", "NtUnloadDriver", "NtOpenDirectoryObject", "UnhookWindowsHookEx", 
                            "NtFreeVirtualMemory", "FindFirstFileExA", "OutputDebugStringA", "RegQueryValueExA",
                              "SendNotifyMessageA", "RegDeleteKeyA", "GlobalMemoryStatusEx", "FindWindowA", 
                              "ReadCabinetState", "DnsQuery_W", "InternetQueryOptionA", 
                              "SetFileInformationByHandle", "GetAdaptersInfo", "NtQueryAttributesFile", 
                              "FindFirstFileExW", "NtEnumerateValueKey", "CopyFileExW", "WSASendTo", 
                              "GetBestInterfaceEx", "Process32FirstW", "GetFileInformationByHandle", 
                              "InternetCloseHandle", "CryptProtectMemory", "InternetGetConnectedStateExW", 
                              "SetFileAttributesW", "NtOpenSection", "GetVolumeNameForVolumeMountPointW", 
                              "CertCreateCertificateContext", "WSARecv", "CoCreateInstance", 
                              "RtlDecompressBuffer", "timeGetTime", "HttpOpenRequestA", "SetFilePointer", 
                              "NtQueryDirectoryFile", "GetSystemTimeAsFileTime", "URLDownloadToFileW", 
                              "FindWindowExW", "DeleteFileW", "NtSuspendThread", "GetCursorPos", 
                              "OpenSCManagerW", "DecryptMessage", "GetUserNameExA", "SetInformationJobObject", 
                              "NtDeviceIoControlFile", "NtLoadDriver", "FindResourceA", "InternetOpenUrlA", 
                              "GetUserNameA", "ReadProcessMemory", "InternetOpenW", "GetKeyboardState", 
                              "GetTempPathW", "RegDeleteKeyW", "NtWriteFile", "SetStdHandle", "LoadStringW", 
                              "gethostbyname", "sendto", "FindWindowW", "NtOpenFile", "GetDiskFreeSpaceW", 
                              "InternetConnectW", "NtCreateFile", "FindResourceExA", "NtResumeThread", 
                              "NetGetJoinInformation", "RegQueryInfoKeyW", "GetNativeSystemInfo", "GetKeyState",
                              "GetFileVersionInfoSizeW", "GetDiskFreeSpaceExW", "WNetGetProviderNameW", 
                              "NtCreateSection", "GetFileVersionInfoExW", "CreateDirectoryExW", 
                              "InternetCrackUrlA", "GetUserNameW", "GetTimeZoneInformation", 
                              "CreateDirectoryW", "GetAsyncKeyState", "GetFileSizeEx", "MoveFileWithProgressW",
                              "GetUserNameExW", "NtEnumerateKey", "SetEndOfFile", "RemoveDirectoryW", 
                              "InternetOpenA", "IsDebuggerPresent", "LookupPrivilegeValueW", "SizeofResource", 
                              "NtDeleteFile", "GetComputerNameA", "NetShareEnum", "WSASend", "NtDeleteKey", 
                              "LdrUnloadDll", "Thread32First", "WriteConsoleW", "GetComputerNameW", 
                              "CryptProtectData", "CryptUnprotectMemory", "LookupAccountSidW", 
                              "CryptAcquireContextW", "NtSetValueKey", "GetFileVersionInfoW", 
                              "InternetWriteFile", "GlobalMemoryStatus", "GetFileAttributesW", 
                              "GetFileVersionInfoSizeExW", "FindResourceW", "HttpSendRequestW", 
                              "NtSetInformationFile", "SetFileTime", "GetSystemMetrics", "GetVolumePathNameW",
                              "GetAddrInfoW", "FindWindowExA", "CopyFileA", "GetSystemDirectoryW", 
                              "IWbemServices_ExecMethod", "NtLoadKey2", "SHGetSpecialFolderLocation", 
                              "DnsQuery_A", "InternetOpenUrlW", "ObtainUserAgentString", "RegSetValueExA", 
                              "ShellExecuteExW", "RegisterHotKey", "getsockname", "NtQuerySystemInformation", 
                              "LoadResource", "RegCreateKeyExW", "CryptDecodeObjectEx", "DeviceIoControl", 
                              "CryptCreateHash", "NetUserGetInfo", "WSASocketW", "Module32NextW", 
                              "FindResourceExW", "UuidCreate", "InternetGetConnectedStateExA", 
                              "NtQueryMultipleValueKey", "CryptEncrypt", "DeleteUrlCacheEntryW", 
                              "NtDuplicateObject", "CoCreateInstanceEx", "closesocket", "NtDelayExecution", 
                              "NtCreateKey", "NtSaveKey", "RegEnumKeyW", "RegCloseKey", "NtLoadKey", "recvfrom", 
                              "select", "accept", "bind", "recv", "InternetReadFile", "send", "socket", "listen", 
                              "connect", "setsockopt", "NtQueryKey", "GetVolumePathNamesForVolumeNameW", 
                              "GetForegroundWindow", "Process32NextW", "InternetCrackUrlW", "getaddrinfo", 
                              "CertOpenStore", "InternetConnectA", "SetFilePointerEx", "GetFileSize", "WSAStartup", 
                              "DeleteUrlCacheEntryA", "WriteProcessMemory", "RegEnumValueW", 
                              "NtAllocateVirtualMemory", "SHGetFolderPathW", "RegEnumKeyExW", "RegOpenKeyExA", 
                              "AssignProcessToJobObject", "NtQueryValueKey", "HttpSendRequestA", "Module32FirstW", 
                              "GetShortPathNameW", "GetFileInformationByHandleEx", "NtMapViewOfSection", 
                              "RegDeleteValueA", "RegCreateKeyExA", "NtDeleteValueKey", "OpenSCManagerA", 
                              "SendNotifyMessageW", "GetAdaptersAddresses", "system", "GetSystemWindowsDirectoryW", 
                              "RegDeleteValueW", "CertOpenSystemStoreA", "NtWriteVirtualMemory", "WriteConsoleA", 
                              "GetSystemDirectoryA", "GetSystemInfo", "GetSystemWindowsDirectoryA", 
                              "NtQueryFullAttributesFile", "InternetSetOptionA", "DrawTextExA", 
                              "NetUserGetLocalGroups", "MessageBoxTimeoutW", "MessageBoxTimeoutA", 
                              "NtGetContextThread", "RegEnumValueA", "CreateToolhelp32Snapshot", "CryptGenKey", 
                              "CryptExportKey", "InternetGetConnectedState", "RtlCompressBuffer", "CoGetClassObject", 
                              "InternetSetStatusCallback", "CreateJobObjectW", "CryptHashData", "CreateActCtxW", 
                              "NtMakeTemporaryObject", "DrawTextExW", "RegQueryInfoKeyA", "NtProtectVirtualMemory", 
                              "RegQueryValueExW", "ioctlsocket", "RegSetValueExW", "NtUnmapViewOfSection", 
                              "NtCreateMutant", "NtSetContextThread", "RegEnumKeyExA", "IWbemServices_ExecQuery", 
                              "CryptUnprotectData", "CertOpenSystemStoreW", "NtOpenMutant", "SearchPathW", 
                              "GetFileAttributesExW", "CryptAcquireContextA", "WSAConnect"],
}